### ISSUE TITLE
plugin-menu Broken after 7.3.0 Update

### ISSUE THREAD

**Issue by ajboni** [enpitsuLin/milkdown-lab#70]
After updating milkdown to 7.3.0 `@milkdown-lab/plugin-menu` does not work:

```
MilkdownError: Context "rootDOM" not found, do you forget to inject it?
    at p (index.ts:13:3)
    at G.get (container.ts:22:13)
    at L.use (ctx.ts:88:28)
    at L.get (ctx.ts:92:80)
    at Object.view (index.js:138:24)
    at EditorView.updatePluginViews (index.js:5255:55)
    at new EditorView (index.js:5087:14)
    at editor-view.ts:112:18
    at async editor.ts:143:23
    at async Promise.all (:5173/index 5)
```

**Comment by enpitsuLin** [comment]
This is due to the different versions of the dependencies, I'm too busy to update the dependencies these days

I may spend some time this weekend upgrading the dependencies!

**Comment by enpitsuLin** [comment]
already published, may you check if this issue still exists?

**Comment by ajboni** [comment]
It works! Thank you very much for your work and quick reply!!!
